### ISSUE TITLE
[Feature] Update and clean up the Readme for Miranum IDE and all of its plugins

### ISSUE THREAD

**Issue by Hafflgav** [FlowSquad/miranum-docs#24]
- [x] Description created 
- [x] Reviewed by peer (24 hr window): <tag-person-here>
- [ ] Prioritised

# Description 
To be appealing for developers and to enable them to get started quickly we need to have an appealing Readme similarly to other vs-code extensions (e.g. Docker).

## Sub-Tasks 
```[tasklist]
### Tasks
- [ ] Add basic Readmes (adding badges, a couple of hints, latest features) 
- [ ] Extend the Readmes with pictures, a better description of the features and a getting started section
```
