### ISSUE TITLE
[Feature] Update documentation for Miranum Connect

### ISSUE THREAD

**Issue by Hafflgav** [FlowSquad/miranum-docs#25]
- [x] Description created 
- [x] Reviewed by peer (24 hr window): <tag-person-here>
- [x] Prioritised

# Description 
To be appealing for developers and to enable them to get started quickly we need to have a complete documentation. This is currently not the case. 

## Sub-Tasks 
```[tasklist]
### Tasks
- [x] Analyse what's currently missing
- [x] Create new documentation pages to make the usage of Miranum-Connect clearer
```

**Comment by Hafflgav** [comment]
* The documentation does not feature a lot info which miranum functionalities are currently supported
* In addition it does not give any insight how to use it (e.g. add maven dependency)
