### ISSUE TITLE
[Feature] Update documentation for Miranum IDE

### ISSUE THREAD

**Issue by Hafflgav** [FlowSquad/miranum-docs#26]
- [x] Description created 
- [x] Reviewed by peer (24 hr window): @peterhnm 
- [ ] Prioritised

# Description 
To be appealing for developers and to enable them to get started quickly we need to have a correct and feature complete documentation. 

## Sub-Tasks 
```[tasklist]
### Tasks
- [ ] Check current content (especially whether it is still accurate)  
- [ ] Identify missing content 
- [ ] Write documentation pages for that missing content
```

**Comment by peterhnm** [comment]
@Hafflgav Currently we don't have any documentation for the Miranum Modeler. I would start with that because I recently moved the Modeler into our monorepo.

**Comment by Hafflgav** [comment]
That would be great @peterhnm! 
There is a [guide](https://miranum.com/docs/guides/getting-started/getting-started-web-ide-guide) which was written a while ago. Maybe you can check whether this one is still up to date.

**Comment by peterhnm** [comment]
@Hafflgav I created some gifs for the docu. Can you have a quick look at them if they are ok?

**Comment by Hafflgav** [comment]
Thanks for creating these gifs @peterhnm! 👍 
I think they are ideal as a feature-overview. 

Though I want to put one point down for discussion: 
The usage of gif's in documentation can be difficult since they lack of accessibility. If you have someone visually impaired they might struggle with finding out what the heck this tool is doing. 

I know that guides in the Camunda Documentation have very elaborate steps which can be followed by the user to complete it. Pictures are just there for support. 
That might be a little nit-picky but I think increasing accessibility right from start is an important thing to do. 💭 

I would stick to the gifs since they are actually really nice but would try to add some text describing what you are doing below them. (maybe you can find some inspiration [here](https://docs.camunda.io/docs/guides/model-your-first-process/))

**Comment by peterhnm** [comment]
Following docus have to be created or updated:
* Miranum Form Builder
* Miranum JSON Forms
* Miranum Console
* [Getting started with Miranum IDE](https://github.com/FlowSquad/miranum-docs/blob/main/docs/guides/getting-started/gettingstarted-ide.md)
