### ISSUE TITLE
[Refactor] Move Pizza-Order example to Docs

### ISSUE THREAD

**Issue by Hafflgav** [FlowSquad/miranum-docs#31]
- [x] Description created
- [x] Reviewed by peer: @rami-nk 
- [x] Prioritised

# Description
After having released the first snapshot version of miranum-connect we want to move our big examples out to the consulting repository. In addition all the information needs to be added to the "Guides" section of our repository. 
This allows a user who visits our documentation to search for and find the information in this guide. 

## Sub-Tasks
```[tasklist]
### Tasks
- [x] Refactor Pizza Order example so that it runs in the miranum-consulting repository
- [x] Remove it from the miranum repository
- [x] Add readme to the documentation and refactor it if needed
```
